#pragma once
#define NUM_RACES 9
#define NUM_CLASSES 12
#define NUM_STATS 6

enum DND_RACE { DWARF, ELF, HALFLING, HUMAN, DRAGONBORN, GNOME, HALF_ELF, HALF_ORC, TIEFLING };
enum DND_CLASS { BARBARIAN, BARD, CLERIC, DRUID, FIGHTER, MONK, PALADIN, RANGER, ROGUE, SORCERER, WARLOCK, WIZARD };
enum DND_STAT { STRENGTH, DEXTERITY, CONSTITUTION, INTELLIGENCE, WISDOM, CHARISMA};
